spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/uaa/user
    client:
      client-id: acme
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://10.1.5.92:3306/dev
    username: root
    password: root
    initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
