spring.profiles.active: development
---
spring:
  profiles: development
  neo4j:
    host: 10.1.5.92
    port: 7474
    uri: http://10.1.5.92:7474
    username: neo4j
    password: shiny
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.1.5.71:8761/eureka/
