spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
  datasource:
    platform: mysql
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/uaa/user
    client:
      client-id: acme
  enable-csrf: false
---
spring:
  profiles: development
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://10.1.5.92:3306/dev
    username: root
    password: root
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
  enable-csrf: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
